[package]
name = "smartscp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathdiff = "0.2.1"
ssh2 = "0.9"
ssh2-config = "0.1.6"
walkdir = "2"
shellexpand = "2.1"
users = "0.11"
